### ISSUE TITLE
Unicode vs Ascii issue 

### ISSUE THREAD

**Issue by srcr** [digitalshadows/orca#1]
Running:
`orca-recon enum services_shodan test`

stops in an exception after enumerating various records with the following error message:
`Exception 'ascii' codec can't encode character '\xe9' in position 1025: ordinal not in range(128)`

it looks like shodan gives a unicode char where the script expects an ascii

**Comment by RcDS** [comment]
Thanks for the report. We are having some trouble identifying the exact source of this bug. Is there any more information you can provide us so we can replicate this error?

**Comment by srcr** [comment]
The most I got is this:

```
IP Address - 193.70.122.154 [ns3060682.ip-193-70-122.eu]
       Ports: 8880,25,80,465,22,8443,21,110,53,143,995,443,993
     Modules: https-simple-new,smtp,http,smtps,ssh,https,ftp,pop3,dns-tcp,dns-udp,imap,pop3-ssl,https,imap-ssl
   AS Number: AS16276
    Netblock: 193.70.0.0/17
Organization: OVH SAS
     Country: FRA
         CPE: smtp:cpe:/a:postfix:postfix,http:cpe:/a:igor_sysoev:nginx,smtps:cpe:/a:postfix:postfix,ssh:cpe:/a:openbsd:openssh:6.7p1,cpe:/o:debian:debian_linux,cpe:/o:linux:linux_kernel,ftp:cpe:/a:proftpd:proftpd,https:cpe:/a:igor_sysoev:nginx
Enumerating [193.70.122.154  ]:   2%|▏      | 77/4237 [10:11<7:53:48,  6.83s/it]Exception 'ascii' codec can't encode character '\xe9' in position 1025: ordinal not in range(128)

```

So it looks like there is a unicode character in the shodan output, but can't pinpoint is better than this. I hope the IP address helps.

**Comment by RcDS** [comment]
We were unable to replicate this error directly, but we have added in a bunch of additional validation which should catch this error. Closing this for now.
